-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1 List the number of films per category. 
Select c.name as Category, COUNT(f.film_id) as Film_Count
FROM Film_category as fc
JOIN film as f on f.film_id = fc.film_id
JOIN category as c on c.category_id = fc.category_id
GROUP BY Category;

-- 2 Retrieve the store ID, city, and country for each store.
SELECT s.store_id as Store, cit.city, co.country
FROM address ad
JOiN store s on s.address_id = ad.address_id
JOIN city cit on cit.city_id = ad.city_id
JOIN country co on co.country_id = cit.country_id
Group by Store;

-- 3 Calculate the total revenue generated by each store in dollars. 
SELECT s.store_id, cit.city, co.country, SUM(p.amount) as total_revenue
FROM store s
JOIN address ad on ad.address_id = s.address_id
JOIN city cit on cit.city_id = ad.city_id
JOIN country co on co.country_id = cit.country_id
JOIN staff  ON s.store_id = staff.store_id
JOIN payment p ON p.staff_id = staff.staff_id
GROUP BY s.store_id, cit.city, co.country;

-- Determine the average running time of films for each category. 
SELECT c.name as category, 
Concat(FLOOR(AVG(f.length)/60),' : ', FLOOR(AVG(f.length)) % 60) as average_running_time
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON c.category_id = fc.category_id
GROUP BY category;